### ISSUE TITLE
Used Ender Intervention on my own summoned Hell Cows and cannot summon new ones even tough killed the old ones

### ISSUE THREAD

**Issue by FrostedNova** [Mithion/ArsMagica2#1130]

**Comment by Mithion** [comment]
For future bugs please follow these guidelines: http://pastebin.com/29r0Nhe0

**Comment by Xyphius** [comment]
This issue has been resolved in development and needs to be tested.

**Comment by jjtParadox** [comment]
Just tested, and it appears that the Intervention spells have no effect on summons.

The particle effects still show, which is a minor bug, but this main bug can probably be closed.

**Comment by jjtParadox** [comment]
@Mithion any update on this issue?

**Comment by c62624** [comment]
I just tested this and the problem didn't occur. The spell did teleport the summon.

**Comment by Kolatra** [comment]
Closing as it seems to have been resolved.
